[2023-09-06 17:28:15,271] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:28:17,418] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:28:18,197] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:28:18] "GET /tutores HTTP/1.1" 200 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:28:57,937] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:28:58,075] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:29:57,423] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:29:57,683] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:30:00,080] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:30:03,452] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:30:06,044] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:30:06,129] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:30:41,616] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:30:42,576] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:30:42] "POST /tutor HTTP/1.1" 200 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:31:07,177] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:31:07,846] WARNING add_tutor() L60   Erro ao adicionar tutor 'Jos√©', Tutor de mesmo nome j√° salvo na base :/ - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py L60  
[2023-09-06 17:31:07,847] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:31:07] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:12,303] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:12,440] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:18,614] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:32:19,932] WARNING add_tutor() L60   Erro ao adicionar tutor 'Jos√©', Tutor de mesmo nome j√° salvo na base :/ - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py L60  
[2023-09-06 17:32:19,934] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:32:19] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:26,862] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:32:27,536] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:32:27] "POST /tutor HTTP/1.1" 200 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:44,077] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:44,198] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:46,167] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:32:46,907] WARNING add_tutor() L60   Erro ao adicionar tutor 'Jos√©', Tutor de mesmo nome j√° salvo na base :/ - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py L60  
[2023-09-06 17:32:46,910] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:32:46] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:55,534] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:55,956] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:32:58,072] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:32:58,826] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:32:58,832] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:32:58] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:33:32,191] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:33:32,867] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:33:32,868] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:33:32] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:33:58,400] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
